
CREATE VIEW STOPOVER(FlightNum1, DepartureTime1, ArrivalTime1, StopOverAirportID,
            FlightNum2, DepartureTime2, ArrivalTime2) AS
SELECT f1.FLIGHTNUM, f1.DEPARTURETIME, f1.ARRIVALTIME, f1.DESTINATION, f2.FLIGHTNUM,
       f2.DEPARTURETIME, f2.ARRIVALTIME
FROM FLIGHTS f1, FLIGHTS f2
WHERE f1.ORIGIN = 'SFO' AND f2.DESTINATION = 'JFK' 
       AND f1.DESTINATION = f2.ORIGIN
       AND f2.DEPARTURETIME >= f1.ARRIVALTIME + '00:30:00'
       AND f2.DEPARTURETIME <= f1.ARRIVALTIME + '02:00:00'; 

SELECT * FROM STOPOVER;
DROP VIEW STOPOVER;
